/**
 * FSS Financial Services
 * This service allows to submit payments, purchases and sales Items to SBBs financial system FSS based on SAP Hybris Billing. Depending on the agreed functionalities the Items can be priced, validated, enriched, posted in the subledger and reported. For more information please check the FSS website or contact the team.
 *
 * OpenAPI spec version: 1.0.1
 * Contact: dl_fss_all@sbb.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.api

import io.swagger.client.model.PaymentDocuments
import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object PaymentDocumentApi {

  /**
   * 
   * 
   * Expected answers:
   *   code 201 :  (Item(s) successfully created in FSS SAP Brim)
   *   code 400 :  (Bad request)
   *   code 401 :  (Unauthorized)
   *   code 500 :  (Internal server error)
   * 
   * @param paymentDocuments PaymentItems includes 1 full payment/refund or up to n partial payments for one business case with a customer
   */
  def v1PaymentDocumentsPost(paymentDocuments: PaymentDocuments): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.POST, "https://localhost", "/v1/PaymentDocuments", "application/json")
      .withBody(paymentDocuments)
      .withSuccessResponse[Unit](201)
      .withErrorResponse[Unit](400)
      .withErrorResponse[Unit](401)
      .withErrorResponse[Unit](500)
      

}

